// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0--rc2
// source: remotefs/v1/pty.proto

package remotefsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error_Kind int32

const (
	Error_KIND_UNSPECIFIED          Error_Kind = 0
	Error_KIND_UNAUTHENTICATED      Error_Kind = 1
	Error_KIND_DAEMON_NOT_CONNECTED Error_Kind = 2
	Error_KIND_SESSION_BUSY         Error_Kind = 3
	Error_KIND_SPAWN_FAILED         Error_Kind = 4
	Error_KIND_PROTOCOL             Error_Kind = 5
	Error_KIND_RATE_LIMITED         Error_Kind = 6
	Error_KIND_INTERNAL             Error_Kind = 99
)

// Enum value maps for Error_Kind.
var (
	Error_Kind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "KIND_UNAUTHENTICATED",
		2:  "KIND_DAEMON_NOT_CONNECTED",
		3:  "KIND_SESSION_BUSY",
		4:  "KIND_SPAWN_FAILED",
		5:  "KIND_PROTOCOL",
		6:  "KIND_RATE_LIMITED",
		99: "KIND_INTERNAL",
	}
	Error_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":          0,
		"KIND_UNAUTHENTICATED":      1,
		"KIND_DAEMON_NOT_CONNECTED": 2,
		"KIND_SESSION_BUSY":         3,
		"KIND_SPAWN_FAILED":         4,
		"KIND_PROTOCOL":             5,
		"KIND_RATE_LIMITED":         6,
		"KIND_INTERNAL":             99,
	}
)

func (x Error_Kind) Enum() *Error_Kind {
	p := new(Error_Kind)
	*p = x
	return p
}

func (x Error_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_remotefs_v1_pty_proto_enumTypes[0].Descriptor()
}

func (Error_Kind) Type() protoreflect.EnumType {
	return &file_remotefs_v1_pty_proto_enumTypes[0]
}

func (x Error_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Kind.Descriptor instead.
func (Error_Kind) EnumDescriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{7, 0}
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientFrame_Attach
	//	*ClientFrame_Stdin
	//	*ClientFrame_Resize
	//	*ClientFrame_Detach
	Payload       isClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetPayload() isClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientFrame) GetAttach() *AttachReq {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientFrame) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ClientFrame) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ClientFrame) GetDetach() *Detach {
	if x != nil {
		if x, ok := x.Payload.(*ClientFrame_Detach); ok {
			return x.Detach
		}
	}
	return nil
}

type isClientFrame_Payload interface {
	isClientFrame_Payload()
}

type ClientFrame_Attach struct {
	Attach *AttachReq `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type ClientFrame_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ClientFrame_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ClientFrame_Detach struct {
	Detach *Detach `protobuf:"bytes,4,opt,name=detach,proto3,oneof"`
}

func (*ClientFrame_Attach) isClientFrame_Payload() {}

func (*ClientFrame_Stdin) isClientFrame_Payload() {}

func (*ClientFrame_Resize) isClientFrame_Payload() {}

func (*ClientFrame_Detach) isClientFrame_Payload() {}

type AttachReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InitialSize   *Resize                `protobuf:"bytes,2,opt,name=initial_size,json=initialSize,proto3" json:"initial_size,omitempty"`
	Term          string                 `protobuf:"bytes,3,opt,name=term,proto3" json:"term,omitempty"`
	ExtraEnv      []string               `protobuf:"bytes,15,rep,name=extra_env,json=extraEnv,proto3" json:"extra_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachReq) Reset() {
	*x = AttachReq{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachReq) ProtoMessage() {}

func (x *AttachReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachReq.ProtoReflect.Descriptor instead.
func (*AttachReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{1}
}

func (x *AttachReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachReq) GetInitialSize() *Resize {
	if x != nil {
		return x.InitialSize
	}
	return nil
}

func (x *AttachReq) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *AttachReq) GetExtraEnv() []string {
	if x != nil {
		return x.ExtraEnv
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	XPixel        uint32                 `protobuf:"varint,3,opt,name=x_pixel,json=xPixel,proto3" json:"x_pixel,omitempty"`
	YPixel        uint32                 `protobuf:"varint,4,opt,name=y_pixel,json=yPixel,proto3" json:"y_pixel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{2}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetXPixel() uint32 {
	if x != nil {
		return x.XPixel
	}
	return 0
}

func (x *Resize) GetYPixel() uint32 {
	if x != nil {
		return x.YPixel
	}
	return 0
}

type Detach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detach) Reset() {
	*x = Detach{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detach) ProtoMessage() {}

func (x *Detach) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detach.ProtoReflect.Descriptor instead.
func (*Detach) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{3}
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerFrame_Attached
	//	*ServerFrame_Stdout
	//	*ServerFrame_Exited
	//	*ServerFrame_Error
	Payload       isServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{4}
}

func (x *ServerFrame) GetPayload() isServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerFrame) GetAttached() *Attached {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Attached); ok {
			return x.Attached
		}
	}
	return nil
}

func (x *ServerFrame) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ServerFrame) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_Attached struct {
	Attached *Attached `protobuf:"bytes,1,opt,name=attached,proto3,oneof"`
}

type ServerFrame_Stdout struct {
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type ServerFrame_Exited struct {
	Exited *Exited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ServerFrame_Attached) isServerFrame_Payload() {}

func (*ServerFrame_Stdout) isServerFrame_Payload() {}

func (*ServerFrame_Exited) isServerFrame_Payload() {}

func (*ServerFrame_Error) isServerFrame_Payload() {}

type Attached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attached) Reset() {
	*x = Attached{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attached) ProtoMessage() {}

func (x *Attached) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attached.ProtoReflect.Descriptor instead.
func (*Attached) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{5}
}

func (x *Attached) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Attached) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Signal        uint32                 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{6}
}

func (x *Exited) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Exited) GetSignal() uint32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Error_Kind             `protobuf:"varint,1,opt,name=kind,proto3,enum=remotefs.v1.Error_Kind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_remotefs_v1_pty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_pty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_pty_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetKind() Error_Kind {
	if x != nil {
		return x.Kind
	}
	return Error_KIND_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_remotefs_v1_pty_proto protoreflect.FileDescriptor

const file_remotefs_v1_pty_proto_rawDesc = "" +
	"\n" +
	"\x15remotefs/v1/pty.proto\x12\vremotefs.v1\"\xc0\x01\n" +
	"\vClientFrame\x120\n" +
	"\x06attach\x18\x01 \x01(\v2\x16.remotefs.v1.AttachReqH\x00R\x06attach\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12-\n" +
	"\x06resize\x18\x03 \x01(\v2\x13.remotefs.v1.ResizeH\x00R\x06resize\x12-\n" +
	"\x06detach\x18\x04 \x01(\v2\x13.remotefs.v1.DetachH\x00R\x06detachB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\tAttachReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\finitial_size\x18\x02 \x01(\v2\x13.remotefs.v1.ResizeR\vinitialSize\x12\x12\n" +
	"\x04term\x18\x03 \x01(\tR\x04term\x12\x1b\n" +
	"\textra_env\x18\x0f \x03(\tR\bextraEnv\"b\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x17\n" +
	"\ax_pixel\x18\x03 \x01(\rR\x06xPixel\x12\x17\n" +
	"\ay_pixel\x18\x04 \x01(\rR\x06yPixel\"\b\n" +
	"\x06Detach\"\xc2\x01\n" +
	"\vServerFrame\x123\n" +
	"\battached\x18\x01 \x01(\v2\x15.remotefs.v1.AttachedH\x00R\battached\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x12-\n" +
	"\x06exited\x18\x03 \x01(\v2\x13.remotefs.v1.ExitedH\x00R\x06exited\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x12.remotefs.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\";\n" +
	"\bAttached\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\"4\n" +
	"\x06Exited\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\rR\x06signal\"\x91\x02\n" +
	"\x05Error\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.remotefs.v1.Error.KindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14KIND_UNAUTHENTICATED\x10\x01\x12\x1d\n" +
	"\x19KIND_DAEMON_NOT_CONNECTED\x10\x02\x12\x15\n" +
	"\x11KIND_SESSION_BUSY\x10\x03\x12\x15\n" +
	"\x11KIND_SPAWN_FAILED\x10\x04\x12\x11\n" +
	"\rKIND_PROTOCOL\x10\x05\x12\x15\n" +
	"\x11KIND_RATE_LIMITED\x10\x06\x12\x11\n" +
	"\rKIND_INTERNAL\x10c2M\n" +
	"\tRemotePTY\x12@\n" +
	"\x06Attach\x12\x18.remotefs.v1.ClientFrame\x1a\x18.remotefs.v1.ServerFrame(\x010\x01B5Z3flyingEirc/Rclaude/api/proto/remotefs/v1;remotefsv1b\x06proto3"

var (
	file_remotefs_v1_pty_proto_rawDescOnce sync.Once
	file_remotefs_v1_pty_proto_rawDescData []byte
)

func file_remotefs_v1_pty_proto_rawDescGZIP() []byte {
	file_remotefs_v1_pty_proto_rawDescOnce.Do(func() {
		file_remotefs_v1_pty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remotefs_v1_pty_proto_rawDesc), len(file_remotefs_v1_pty_proto_rawDesc)))
	})
	return file_remotefs_v1_pty_proto_rawDescData
}

var (
	file_remotefs_v1_pty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_remotefs_v1_pty_proto_msgTypes  = make([]protoimpl.MessageInfo, 8)
	file_remotefs_v1_pty_proto_goTypes   = []any{
		(Error_Kind)(0),     // 0: remotefs.v1.Error.Kind
		(*ClientFrame)(nil), // 1: remotefs.v1.ClientFrame
		(*AttachReq)(nil),   // 2: remotefs.v1.AttachReq
		(*Resize)(nil),      // 3: remotefs.v1.Resize
		(*Detach)(nil),      // 4: remotefs.v1.Detach
		(*ServerFrame)(nil), // 5: remotefs.v1.ServerFrame
		(*Attached)(nil),    // 6: remotefs.v1.Attached
		(*Exited)(nil),      // 7: remotefs.v1.Exited
		(*Error)(nil),       // 8: remotefs.v1.Error
	}
)
var file_remotefs_v1_pty_proto_depIdxs = []int32{
	2, // 0: remotefs.v1.ClientFrame.attach:type_name -> remotefs.v1.AttachReq
	3, // 1: remotefs.v1.ClientFrame.resize:type_name -> remotefs.v1.Resize
	4, // 2: remotefs.v1.ClientFrame.detach:type_name -> remotefs.v1.Detach
	3, // 3: remotefs.v1.AttachReq.initial_size:type_name -> remotefs.v1.Resize
	6, // 4: remotefs.v1.ServerFrame.attached:type_name -> remotefs.v1.Attached
	7, // 5: remotefs.v1.ServerFrame.exited:type_name -> remotefs.v1.Exited
	8, // 6: remotefs.v1.ServerFrame.error:type_name -> remotefs.v1.Error
	0, // 7: remotefs.v1.Error.kind:type_name -> remotefs.v1.Error.Kind
	1, // 8: remotefs.v1.RemotePTY.Attach:input_type -> remotefs.v1.ClientFrame
	5, // 9: remotefs.v1.RemotePTY.Attach:output_type -> remotefs.v1.ServerFrame
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_remotefs_v1_pty_proto_init() }
func file_remotefs_v1_pty_proto_init() {
	if File_remotefs_v1_pty_proto != nil {
		return
	}
	file_remotefs_v1_pty_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Attach)(nil),
		(*ClientFrame_Stdin)(nil),
		(*ClientFrame_Resize)(nil),
		(*ClientFrame_Detach)(nil),
	}
	file_remotefs_v1_pty_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerFrame_Attached)(nil),
		(*ServerFrame_Stdout)(nil),
		(*ServerFrame_Exited)(nil),
		(*ServerFrame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remotefs_v1_pty_proto_rawDesc), len(file_remotefs_v1_pty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remotefs_v1_pty_proto_goTypes,
		DependencyIndexes: file_remotefs_v1_pty_proto_depIdxs,
		EnumInfos:         file_remotefs_v1_pty_proto_enumTypes,
		MessageInfos:      file_remotefs_v1_pty_proto_msgTypes,
	}.Build()
	File_remotefs_v1_pty_proto = out.File
	file_remotefs_v1_pty_proto_goTypes = nil
	file_remotefs_v1_pty_proto_depIdxs = nil
}
