// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0--rc2
// source: remotefs/v1/pty.proto

package remotefsv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemotePTY_Attach_FullMethodName = "/remotefs.v1.RemotePTY/Attach"
)

// RemotePTYClient is the client API for RemotePTY service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemotePTYClient interface {
	// Attach establishes a PTY session over a bidirectional stream.
	// The first client frame must be attach, and the first server frame must be
	// attached or error.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type remotePTYClient struct {
	cc grpc.ClientConnInterface
}

func NewRemotePTYClient(cc grpc.ClientConnInterface) RemotePTYClient {
	return &remotePTYClient{cc}
}

func (c *remotePTYClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemotePTY_ServiceDesc.Streams[0], RemotePTY_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemotePTY_AttachClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// RemotePTYServer is the server API for RemotePTY service.
// All implementations must embed UnimplementedRemotePTYServer
// for forward compatibility.
type RemotePTYServer interface {
	// Attach establishes a PTY session over a bidirectional stream.
	// The first client frame must be attach, and the first server frame must be
	// attached or error.
	Attach(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedRemotePTYServer()
}

// UnimplementedRemotePTYServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemotePTYServer struct{}

func (UnimplementedRemotePTYServer) Attach(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedRemotePTYServer) mustEmbedUnimplementedRemotePTYServer() {}
func (UnimplementedRemotePTYServer) testEmbeddedByValue()                   {}

// UnsafeRemotePTYServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemotePTYServer will
// result in compilation errors.
type UnsafeRemotePTYServer interface {
	mustEmbedUnimplementedRemotePTYServer()
}

func RegisterRemotePTYServer(s grpc.ServiceRegistrar, srv RemotePTYServer) {
	// If the following call panics, it indicates UnimplementedRemotePTYServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemotePTY_ServiceDesc, srv)
}

func _RemotePTY_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemotePTYServer).Attach(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemotePTY_AttachServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// RemotePTY_ServiceDesc is the grpc.ServiceDesc for RemotePTY service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemotePTY_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remotefs.v1.RemotePTY",
	HandlerType: (*RemotePTYServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _RemotePTY_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remotefs/v1/pty.proto",
}
