// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0--rc2
// source: remotefs/v1/remotefs.proto

package remotefsv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteFS_Connect_FullMethodName = "/remotefs.v1.RemoteFS/Connect"
)

// RemoteFSClient is the client API for RemoteFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteFSClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, ServerMessage], error)
}

type remoteFSClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteFSClient(cc grpc.ClientConnInterface) RemoteFSClient {
	return &remoteFSClient{cc}
}

func (c *remoteFSClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DaemonMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteFS_ServiceDesc.Streams[0], RemoteFS_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DaemonMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteFS_ConnectClient = grpc.BidiStreamingClient[DaemonMessage, ServerMessage]

// RemoteFSServer is the server API for RemoteFS service.
// All implementations must embed UnimplementedRemoteFSServer
// for forward compatibility.
type RemoteFSServer interface {
	Connect(grpc.BidiStreamingServer[DaemonMessage, ServerMessage]) error
	mustEmbedUnimplementedRemoteFSServer()
}

// UnimplementedRemoteFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteFSServer struct{}

func (UnimplementedRemoteFSServer) Connect(grpc.BidiStreamingServer[DaemonMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRemoteFSServer) mustEmbedUnimplementedRemoteFSServer() {}
func (UnimplementedRemoteFSServer) testEmbeddedByValue()                  {}

// UnsafeRemoteFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteFSServer will
// result in compilation errors.
type UnsafeRemoteFSServer interface {
	mustEmbedUnimplementedRemoteFSServer()
}

func RegisterRemoteFSServer(s grpc.ServiceRegistrar, srv RemoteFSServer) {
	// If the following call panics, it indicates UnimplementedRemoteFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteFS_ServiceDesc, srv)
}

func _RemoteFS_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteFSServer).Connect(&grpc.GenericServerStream[DaemonMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteFS_ConnectServer = grpc.BidiStreamingServer[DaemonMessage, ServerMessage]

// RemoteFS_ServiceDesc is the grpc.ServiceDesc for RemoteFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remotefs.v1.RemoteFS",
	HandlerType: (*RemoteFSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RemoteFS_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "remotefs/v1/remotefs.proto",
}
