// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0--rc2
// source: remotefs/v1/remotefs.proto

package remotefsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeType 描述 fsnotify 上报的变更类型。
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_CREATE      ChangeType = 1
	ChangeType_CHANGE_TYPE_MODIFY      ChangeType = 2
	ChangeType_CHANGE_TYPE_DELETE      ChangeType = 3
	ChangeType_CHANGE_TYPE_RENAME      ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_CREATE",
		2: "CHANGE_TYPE_MODIFY",
		3: "CHANGE_TYPE_DELETE",
		4: "CHANGE_TYPE_RENAME",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_CREATE":      1,
		"CHANGE_TYPE_MODIFY":      2,
		"CHANGE_TYPE_DELETE":      3,
		"CHANGE_TYPE_RENAME":      4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_remotefs_v1_remotefs_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_remotefs_v1_remotefs_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{0}
}

// FileInfo 描述工作区中的一个文件或目录元数据。
// path 字段统一使用 forward slash 相对路径，不包含 leading slash。
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // Unix timestamp (seconds since epoch)
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"` // POSIX 文件权限位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// FileTree 是 FileInfo 的集合，可承载完整或部分目录树。
type FileTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTree) Reset() {
	*x = FileTree{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTree) ProtoMessage() {}

func (x *FileTree) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTree.ProtoReflect.Descriptor instead.
func (*FileTree) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{1}
}

func (x *FileTree) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// FileChange 描述一次文件变更事件。
// RENAME 时 old_path 是旧路径，file.path 是新路径。
type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChangeType             `protobuf:"varint,1,opt,name=type,proto3,enum=remotefs.v1.ChangeType" json:"type,omitempty"`
	File          *FileInfo              `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	OldPath       string                 `protobuf:"bytes,3,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{2}
}

func (x *FileChange) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *FileChange) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileChange) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

type ReadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 0 表示读全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileReq) Reset() {
	*x = ReadFileReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileReq) ProtoMessage() {}

func (x *ReadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileReq.ProtoReflect.Descriptor instead.
func (*ReadFileReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileReq) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type WriteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Append        bool                   `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"` // 0 表示保持原有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileReq) Reset() {
	*x = WriteFileReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileReq) ProtoMessage() {}

func (x *WriteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileReq.ProtoReflect.Descriptor instead.
func (*WriteFileReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{4}
}

func (x *WriteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileReq) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

func (x *WriteFileReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type StatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatReq) Reset() {
	*x = StatReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReq) ProtoMessage() {}

func (x *StatReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReq.ProtoReflect.Descriptor instead.
func (*StatReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{5}
}

func (x *StatReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirReq) Reset() {
	*x = ListDirReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirReq) ProtoMessage() {}

func (x *ListDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirReq.ProtoReflect.Descriptor instead.
func (*ListDirReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirReq) Reset() {
	*x = MkdirReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReq) ProtoMessage() {}

func (x *MkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReq.ProtoReflect.Descriptor instead.
func (*MkdirReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{8}
}

func (x *MkdirReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirReq) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RenameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{9}
}

func (x *RenameReq) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameReq) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

// FileRequest 是 Server 下发给 Daemon 的单条文件操作请求。
type FileRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*FileRequest_Read
	//	*FileRequest_Write
	//	*FileRequest_Stat
	//	*FileRequest_ListDir
	//	*FileRequest_Delete
	//	*FileRequest_Mkdir
	//	*FileRequest_Rename
	Operation     isFileRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{10}
}

func (x *FileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileRequest) GetOperation() isFileRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *FileRequest) GetRead() *ReadFileReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *FileRequest) GetWrite() *WriteFileReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *FileRequest) GetStat() *StatReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *FileRequest) GetListDir() *ListDirReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_ListDir); ok {
			return x.ListDir
		}
	}
	return nil
}

func (x *FileRequest) GetDelete() *DeleteReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *FileRequest) GetMkdir() *MkdirReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *FileRequest) GetRename() *RenameReq {
	if x != nil {
		if x, ok := x.Operation.(*FileRequest_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

type isFileRequest_Operation interface {
	isFileRequest_Operation()
}

type FileRequest_Read struct {
	Read *ReadFileReq `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type FileRequest_Write struct {
	Write *WriteFileReq `protobuf:"bytes,3,opt,name=write,proto3,oneof"`
}

type FileRequest_Stat struct {
	Stat *StatReq `protobuf:"bytes,4,opt,name=stat,proto3,oneof"`
}

type FileRequest_ListDir struct {
	ListDir *ListDirReq `protobuf:"bytes,5,opt,name=list_dir,json=listDir,proto3,oneof"`
}

type FileRequest_Delete struct {
	Delete *DeleteReq `protobuf:"bytes,6,opt,name=delete,proto3,oneof"`
}

type FileRequest_Mkdir struct {
	Mkdir *MkdirReq `protobuf:"bytes,7,opt,name=mkdir,proto3,oneof"`
}

type FileRequest_Rename struct {
	Rename *RenameReq `protobuf:"bytes,8,opt,name=rename,proto3,oneof"`
}

func (*FileRequest_Read) isFileRequest_Operation() {}

func (*FileRequest_Write) isFileRequest_Operation() {}

func (*FileRequest_Stat) isFileRequest_Operation() {}

func (*FileRequest_ListDir) isFileRequest_Operation() {}

func (*FileRequest_Delete) isFileRequest_Operation() {}

func (*FileRequest_Mkdir) isFileRequest_Operation() {}

func (*FileRequest_Rename) isFileRequest_Operation() {}

// FileResponse 是 Daemon 回给 Server 的单条响应。
type FileResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*FileResponse_Content
	//	*FileResponse_Info
	//	*FileResponse_Entries
	Result        isFileResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{11}
}

func (x *FileResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FileResponse) GetResult() isFileResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FileResponse) GetContent() []byte {
	if x != nil {
		if x, ok := x.Result.(*FileResponse_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *FileResponse) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Result.(*FileResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FileResponse) GetEntries() *FileTree {
	if x != nil {
		if x, ok := x.Result.(*FileResponse_Entries); ok {
			return x.Entries
		}
	}
	return nil
}

type isFileResponse_Result interface {
	isFileResponse_Result()
}

type FileResponse_Content struct {
	Content []byte `protobuf:"bytes,4,opt,name=content,proto3,oneof"` // ReadFile 返回
}

type FileResponse_Info struct {
	Info *FileInfo `protobuf:"bytes,5,opt,name=info,proto3,oneof"` // Stat 返回
}

type FileResponse_Entries struct {
	Entries *FileTree `protobuf:"bytes,6,opt,name=entries,proto3,oneof"` // ListDir 返回
}

func (*FileResponse_Content) isFileResponse_Result() {}

func (*FileResponse_Info) isFileResponse_Result() {}

func (*FileResponse_Entries) isFileResponse_Result() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{12}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DaemonMessage 是 Daemon → Server 方向的消息。
type DaemonMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DaemonMessage_FileTree
	//	*DaemonMessage_Change
	//	*DaemonMessage_Response
	//	*DaemonMessage_Heartbeat
	Msg           isDaemonMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonMessage) Reset() {
	*x = DaemonMessage{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonMessage) ProtoMessage() {}

func (x *DaemonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonMessage.ProtoReflect.Descriptor instead.
func (*DaemonMessage) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{13}
}

func (x *DaemonMessage) GetMsg() isDaemonMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DaemonMessage) GetFileTree() *FileTree {
	if x != nil {
		if x, ok := x.Msg.(*DaemonMessage_FileTree); ok {
			return x.FileTree
		}
	}
	return nil
}

func (x *DaemonMessage) GetChange() *FileChange {
	if x != nil {
		if x, ok := x.Msg.(*DaemonMessage_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *DaemonMessage) GetResponse() *FileResponse {
	if x != nil {
		if x, ok := x.Msg.(*DaemonMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *DaemonMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*DaemonMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isDaemonMessage_Msg interface {
	isDaemonMessage_Msg()
}

type DaemonMessage_FileTree struct {
	FileTree *FileTree `protobuf:"bytes,1,opt,name=file_tree,json=fileTree,proto3,oneof"` // 初始全量上报
}

type DaemonMessage_Change struct {
	Change *FileChange `protobuf:"bytes,2,opt,name=change,proto3,oneof"` // 增量变更
}

type DaemonMessage_Response struct {
	Response *FileResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"` // 文件操作响应
}

type DaemonMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*DaemonMessage_FileTree) isDaemonMessage_Msg() {}

func (*DaemonMessage_Change) isDaemonMessage_Msg() {}

func (*DaemonMessage_Response) isDaemonMessage_Msg() {}

func (*DaemonMessage_Heartbeat) isDaemonMessage_Msg() {}

// ServerMessage 是 Server → Daemon 方向的消息。
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Request
	//	*ServerMessage_Heartbeat
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_remotefs_v1_remotefs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_remotefs_v1_remotefs_proto_rawDescGZIP(), []int{14}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetRequest() *FileRequest {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Request struct {
	Request *FileRequest `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type ServerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*ServerMessage_Request) isServerMessage_Msg() {}

func (*ServerMessage_Heartbeat) isServerMessage_Msg() {}

var File_remotefs_v1_remotefs_proto protoreflect.FileDescriptor

const file_remotefs_v1_remotefs_proto_rawDesc = "" +
	"\n" +
	"\x1aremotefs/v1/remotefs.proto\x12\vremotefs.v1\"x\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x03 \x01(\x03R\amodTime\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"7\n" +
	"\bFileTree\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.remotefs.v1.FileInfoR\x05files\"\x7f\n" +
	"\n" +
	"FileChange\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.remotefs.v1.ChangeTypeR\x04type\x12)\n" +
	"\x04file\x18\x02 \x01(\v2\x15.remotefs.v1.FileInfoR\x04file\x12\x19\n" +
	"\bold_path\x18\x03 \x01(\tR\aoldPath\"Q\n" +
	"\vReadFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"h\n" +
	"\fWriteFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06append\x18\x03 \x01(\bR\x06append\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"\x1d\n" +
	"\aStatReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\" \n" +
	"\n" +
	"ListDirReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1f\n" +
	"\tDeleteReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"<\n" +
	"\bMkdirReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"A\n" +
	"\tRenameReq\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"\x91\x03\n" +
	"\vFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\x04read\x18\x02 \x01(\v2\x18.remotefs.v1.ReadFileReqH\x00R\x04read\x121\n" +
	"\x05write\x18\x03 \x01(\v2\x19.remotefs.v1.WriteFileReqH\x00R\x05write\x12*\n" +
	"\x04stat\x18\x04 \x01(\v2\x14.remotefs.v1.StatReqH\x00R\x04stat\x124\n" +
	"\blist_dir\x18\x05 \x01(\v2\x17.remotefs.v1.ListDirReqH\x00R\alistDir\x120\n" +
	"\x06delete\x18\x06 \x01(\v2\x16.remotefs.v1.DeleteReqH\x00R\x06delete\x12-\n" +
	"\x05mkdir\x18\a \x01(\v2\x15.remotefs.v1.MkdirReqH\x00R\x05mkdir\x120\n" +
	"\x06rename\x18\b \x01(\v2\x16.remotefs.v1.RenameReqH\x00R\x06renameB\v\n" +
	"\toperation\"\xe3\x01\n" +
	"\fFileResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1a\n" +
	"\acontent\x18\x04 \x01(\fH\x00R\acontent\x12+\n" +
	"\x04info\x18\x05 \x01(\v2\x15.remotefs.v1.FileInfoH\x00R\x04info\x121\n" +
	"\aentries\x18\x06 \x01(\v2\x15.remotefs.v1.FileTreeH\x00R\aentriesB\b\n" +
	"\x06result\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xf0\x01\n" +
	"\rDaemonMessage\x124\n" +
	"\tfile_tree\x18\x01 \x01(\v2\x15.remotefs.v1.FileTreeH\x00R\bfileTree\x121\n" +
	"\x06change\x18\x02 \x01(\v2\x17.remotefs.v1.FileChangeH\x00R\x06change\x127\n" +
	"\bresponse\x18\x03 \x01(\v2\x19.remotefs.v1.FileResponseH\x00R\bresponse\x126\n" +
	"\theartbeat\x18\x04 \x01(\v2\x16.remotefs.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"\x84\x01\n" +
	"\rServerMessage\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x18.remotefs.v1.FileRequestH\x00R\arequest\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.remotefs.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg*\x89\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHANGE_TYPE_CREATE\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_MODIFY\x10\x02\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x03\x12\x16\n" +
	"\x12CHANGE_TYPE_RENAME\x10\x042Q\n" +
	"\bRemoteFS\x12E\n" +
	"\aConnect\x12\x1a.remotefs.v1.DaemonMessage\x1a\x1a.remotefs.v1.ServerMessage(\x010\x01B5Z3flyingEirc/Rclaude/api/proto/remotefs/v1;remotefsv1b\x06proto3"

var (
	file_remotefs_v1_remotefs_proto_rawDescOnce sync.Once
	file_remotefs_v1_remotefs_proto_rawDescData []byte
)

func file_remotefs_v1_remotefs_proto_rawDescGZIP() []byte {
	file_remotefs_v1_remotefs_proto_rawDescOnce.Do(func() {
		file_remotefs_v1_remotefs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remotefs_v1_remotefs_proto_rawDesc), len(file_remotefs_v1_remotefs_proto_rawDesc)))
	})
	return file_remotefs_v1_remotefs_proto_rawDescData
}

var file_remotefs_v1_remotefs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remotefs_v1_remotefs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_remotefs_v1_remotefs_proto_goTypes = []any{
	(ChangeType)(0),       // 0: remotefs.v1.ChangeType
	(*FileInfo)(nil),      // 1: remotefs.v1.FileInfo
	(*FileTree)(nil),      // 2: remotefs.v1.FileTree
	(*FileChange)(nil),    // 3: remotefs.v1.FileChange
	(*ReadFileReq)(nil),   // 4: remotefs.v1.ReadFileReq
	(*WriteFileReq)(nil),  // 5: remotefs.v1.WriteFileReq
	(*StatReq)(nil),       // 6: remotefs.v1.StatReq
	(*ListDirReq)(nil),    // 7: remotefs.v1.ListDirReq
	(*DeleteReq)(nil),     // 8: remotefs.v1.DeleteReq
	(*MkdirReq)(nil),      // 9: remotefs.v1.MkdirReq
	(*RenameReq)(nil),     // 10: remotefs.v1.RenameReq
	(*FileRequest)(nil),   // 11: remotefs.v1.FileRequest
	(*FileResponse)(nil),  // 12: remotefs.v1.FileResponse
	(*Heartbeat)(nil),     // 13: remotefs.v1.Heartbeat
	(*DaemonMessage)(nil), // 14: remotefs.v1.DaemonMessage
	(*ServerMessage)(nil), // 15: remotefs.v1.ServerMessage
}
var file_remotefs_v1_remotefs_proto_depIdxs = []int32{
	1,  // 0: remotefs.v1.FileTree.files:type_name -> remotefs.v1.FileInfo
	0,  // 1: remotefs.v1.FileChange.type:type_name -> remotefs.v1.ChangeType
	1,  // 2: remotefs.v1.FileChange.file:type_name -> remotefs.v1.FileInfo
	4,  // 3: remotefs.v1.FileRequest.read:type_name -> remotefs.v1.ReadFileReq
	5,  // 4: remotefs.v1.FileRequest.write:type_name -> remotefs.v1.WriteFileReq
	6,  // 5: remotefs.v1.FileRequest.stat:type_name -> remotefs.v1.StatReq
	7,  // 6: remotefs.v1.FileRequest.list_dir:type_name -> remotefs.v1.ListDirReq
	8,  // 7: remotefs.v1.FileRequest.delete:type_name -> remotefs.v1.DeleteReq
	9,  // 8: remotefs.v1.FileRequest.mkdir:type_name -> remotefs.v1.MkdirReq
	10, // 9: remotefs.v1.FileRequest.rename:type_name -> remotefs.v1.RenameReq
	1,  // 10: remotefs.v1.FileResponse.info:type_name -> remotefs.v1.FileInfo
	2,  // 11: remotefs.v1.FileResponse.entries:type_name -> remotefs.v1.FileTree
	2,  // 12: remotefs.v1.DaemonMessage.file_tree:type_name -> remotefs.v1.FileTree
	3,  // 13: remotefs.v1.DaemonMessage.change:type_name -> remotefs.v1.FileChange
	12, // 14: remotefs.v1.DaemonMessage.response:type_name -> remotefs.v1.FileResponse
	13, // 15: remotefs.v1.DaemonMessage.heartbeat:type_name -> remotefs.v1.Heartbeat
	11, // 16: remotefs.v1.ServerMessage.request:type_name -> remotefs.v1.FileRequest
	13, // 17: remotefs.v1.ServerMessage.heartbeat:type_name -> remotefs.v1.Heartbeat
	14, // 18: remotefs.v1.RemoteFS.Connect:input_type -> remotefs.v1.DaemonMessage
	15, // 19: remotefs.v1.RemoteFS.Connect:output_type -> remotefs.v1.ServerMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_remotefs_v1_remotefs_proto_init() }
func file_remotefs_v1_remotefs_proto_init() {
	if File_remotefs_v1_remotefs_proto != nil {
		return
	}
	file_remotefs_v1_remotefs_proto_msgTypes[10].OneofWrappers = []any{
		(*FileRequest_Read)(nil),
		(*FileRequest_Write)(nil),
		(*FileRequest_Stat)(nil),
		(*FileRequest_ListDir)(nil),
		(*FileRequest_Delete)(nil),
		(*FileRequest_Mkdir)(nil),
		(*FileRequest_Rename)(nil),
	}
	file_remotefs_v1_remotefs_proto_msgTypes[11].OneofWrappers = []any{
		(*FileResponse_Content)(nil),
		(*FileResponse_Info)(nil),
		(*FileResponse_Entries)(nil),
	}
	file_remotefs_v1_remotefs_proto_msgTypes[13].OneofWrappers = []any{
		(*DaemonMessage_FileTree)(nil),
		(*DaemonMessage_Change)(nil),
		(*DaemonMessage_Response)(nil),
		(*DaemonMessage_Heartbeat)(nil),
	}
	file_remotefs_v1_remotefs_proto_msgTypes[14].OneofWrappers = []any{
		(*ServerMessage_Request)(nil),
		(*ServerMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remotefs_v1_remotefs_proto_rawDesc), len(file_remotefs_v1_remotefs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remotefs_v1_remotefs_proto_goTypes,
		DependencyIndexes: file_remotefs_v1_remotefs_proto_depIdxs,
		EnumInfos:         file_remotefs_v1_remotefs_proto_enumTypes,
		MessageInfos:      file_remotefs_v1_remotefs_proto_msgTypes,
	}.Build()
	File_remotefs_v1_remotefs_proto = out.File
	file_remotefs_v1_remotefs_proto_goTypes = nil
	file_remotefs_v1_remotefs_proto_depIdxs = nil
}
